# Generated by Django 5.1.6 on 2025-04-27 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo_url',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
    ]
