# Generated by Django 5.1.6 on 2025-05-12 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_userprofile_bio_userprofile_wallet_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='chain_ecosystem',
            field=models.CharField(blank=True, choices=[('BITCOIN', 'Bitcoin'), ('ETHEREUM', 'Ethereum'), ('SOLANA', 'Solana'), ('BINANCE_SMART_CHAIN', 'Binance Smart Chain'), ('CARDANO', 'Cardano'), ('POLKADOT', 'Polkadot'), ('AVALANCHE', 'Avalanche'), ('TRON', 'Tron'), ('COSMOS', 'Cosmos'), ('NEAR', 'Near'), ('TEZOS', 'Tezos'), ('ALGORAND', 'Algorand'), ('FLOW', 'Flow'), ('HEDERA', 'Hedera'), ('RIPPLE', 'Ripple'), ('DOGECOIN', 'Dogecoin'), ('CHIA', 'Chia'), ('STELLAR', 'Stellar'), ('EOS', 'EOS'), ('NEO', 'NEO'), ('VECHAIN', 'VeChain'), ('IOTA', 'IOTA'), ('LISK', 'Lisk'), ('ARK', 'Ark'), ('ZILLIQA', 'Zilliqa'), ('QTUM', 'Qtum'), ('WANCHAIN', 'Wanchain'), ('MULTIVERSX', 'MultiversX'), ('CELO', 'Celo'), ('THORCHAIN', 'THORChain'), ('KLAYTN', 'Klaytn'), ('HARMONY', 'Harmony'), ('SECRET_NETWORK', 'Secret Network'), ('OASIS_NETWORK', 'Oasis Network'), ('SKALE', 'Skale'), ('TELOS', 'Telos'), ('ENERGI', 'Energi'), ('RSK', 'RSK'), ('ERGO', 'Ergo'), ('BERACHAIN', 'Berachain'), ('PLUME_NETWORK', 'Plume Network'), ('TON', 'TON'), ('MONAD', 'Monad'), ('MOVEMENT', 'Movement'), ('SEI', 'Sei'), ('CELESTIA', 'Celestia'), ('POLYGON', 'Polygon'), ('ARBITRUM', 'Arbitrum'), ('OPTIMISM', 'Optimism'), ('BASE', 'Base'), ('MANTLE', 'Mantle'), ('BLAST', 'Blast'), ('STARKNET', 'Starknet'), ('HYPERLEDGER', 'Hyperledger'), ('MAPLE_FINANCE', 'Maple Finance'), ('BABYLON', 'Babylon'), ('DEEPBOOK', 'DeepBook')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='position',
            field=models.CharField(choices=[('ADVISOR', 'Advisor'), ('AMBASSADOR', 'Ambassador'), ('ANALYST', 'Analyst'), ('AUDITOR', 'Auditor'), ('BLOCKCHAIN_ARCHITECT', 'Blockchain Architect'), ('BLOCKCHAIN_DEVELOPER', 'Blockchain Developer'), ('COMMUNITY_MANAGER', 'Community Manager'), ('CO_FOUNDER', 'Co-Founder'), ('CURATOR', 'Curator'), ('DATA_ANALYST', 'Data Analyst'), ('DESIGNER', 'Designer'), ('DEVELOPER', 'Developer'), ('DEVOPS_ENGINEER', 'DevOps Engineer'), ('DAPP_DEVELOPER', 'dApp Developer'), ('ECOSYSTEM_LEAD', 'Ecosystem Lead'), ('ENGINEER', 'Engineer'), ('ETHICAL_HACKER', 'Ethical Hacker'), ('FULL_STACK_DEVELOPER', 'Full-Stack Developer'), ('GAME_DESIGNER', 'Game Designer'), ('GRAPHIC_DESIGNER', 'Graphic Designer'), ('HOST', 'Host'), ('INFRASTRUCTURE_ENGINEER', 'Infrastructure Engineer'), ('INTERN', 'Intern'), ('INVESTOR', 'Investor'), ('KOL', 'KOL'), ('LEGAL_CONSULTANT', 'Legal Consultant'), ('MARKETER', 'Marketer'), ('METAVERSE_ARCHITECT', 'Metaverse Architect'), ('MODERATOR', 'Moderator'), ('NFT_SPECIALIST', 'NFT Specialist'), ('EVENT_ORGANIZER', 'Event Organizer'), ('PRODUCT_MANAGER', 'Product Manager'), ('PROJECT_MANAGER', 'Project Manager'), ('PROTOCOL_DEVELOPER', 'Protocol Developer'), ('RESEARCHER', 'Researcher'), ('SECURITY_ENGINEER', 'Security Engineer'), ('SMART_CONTRACT_DEVELOPER', 'Smart Contract Developer'), ('SOCIAL_MEDIA_MANAGER', 'Social Media Manager'), ('STRATEGIST', 'Strategist'), ('TOKENOMICS_STRATEGIST', 'Tokenomics Strategist'), ('TRADER', 'Trader'), ('VALIDATOR', 'Validator'), ('VENTURE_CAPITALIST', 'Venture Capitalist'), ('CONSULTANT', 'Consultant')], default='MALE', max_length=60, null=True),
        ),
    ]
