# Generated by Django 5.1.6 on 2025-05-12 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_userprofile_chain_ecosystem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='city',
            field=models.CharField(blank=True, choices=[('SAN_FRANCISCO', 'San Francisco, USA'), ('NEW_YORK', 'New York, USA'), ('LONDON', 'London, UK'), ('BERLIN', 'Berlin, Germany'), ('SINGAPORE', 'Singapore'), ('TOKYO', 'Tokyo, Japan'), ('SEOUL', 'Seoul, South Korea'), ('DUBAI', 'Dubai, UAE'), ('TEL_AVIV', 'Tel Aviv, Israel'), ('BANGALORE', 'Bangalore, India'), ('SHANGHAI', 'Shanghai, China'), ('OTHER', 'Other')], max_length=150, null=True),
        ),
    ]
