# Generated by Django 5.1.6 on 2025-05-14 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_userprofile_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='city',
            field=models.CharField(blank=True, choices=[('ABU_DHABI', 'Abu Dhabi'), ('AMSTERDAM', 'Amsterdam'), ('AUSTIN', 'Austin'), ('BALI', 'Bali'), ('BANGALORE', 'Bangalore'), ('BANGKOK', 'Bangkok'), ('BARCELONA', 'Barcelona'), ('BELGRADE', 'Belgrade'), ('BERLIN', 'Berlin'), ('BRNO', 'Brno'), ('BRUSSELS', 'Brussels'), ('BUCHAREST', 'Bucharest'), ('BUENOS_AIRES', 'Buenos Aires'), ('CHIANG_MAI', 'Chiang Mai'), ('DA_NANG', 'Da Nang'), ('DAVOS', 'Davos'), ('DUBAI', 'Dubai'), ('HO_CHI_MINH_CITY', 'Ho Chi Minh City'), ('HONG_KONG', 'Hong Kong'), ('ISTANBUL', 'Istanbul'), ('KUALA_LUMPUR', 'Kuala Lumpur'), ('KYOTO', 'Kyoto'), ('LA_PAZ', 'La Paz'), ('LAGOS', 'Lagos'), ('LISBON', 'Lisbon'), ('LONDON', 'London'), ('LOS_ANGELES', 'Los Angeles'), ('LUGANO', 'Lugano'), ('MADRID', 'Madrid'), ('MALTA', 'Malta'), ('MANILA', 'Manila'), ('MEDELLIN', 'Medellin'), ('MEXICO_CITY', 'Mexico City'), ('MIAMI', 'Miami'), ('MILAN', 'Milan'), ('MONTREAL', 'Montreal'), ('MUNICH', 'Munich'), ('NAIROBI', 'Nairobi'), ('NEW_YORK_CITY', 'New York City'), ('OXFORD', 'Oxford'), ('PARIS', 'Paris'), ('PORTO', 'Porto'), ('PRAGUE', 'Prague'), ('RIO_DE_JANEIRO', 'Rio de Janeiro'), ('ROATAN', 'Roatan'), ('ROME', 'Rome'), ('SALT_LAKE_CITY', 'Salt Lake City'), ('SAN_FRANCISCO', 'San Francisco'), ('SAN_JUAN', 'San Juan'), ('SEOUL', 'Seoul'), ('SINGAPORE', 'Singapore'), ('SPLIT', 'Split'), ('STANFORD', 'Stanford'), ('STOCKHOLM', 'Stockholm'), ('TAIPEI', 'Taipei'), ('TEL_AVIV', 'Tel Aviv'), ('TOKYO', 'Tokyo'), ('TORONTO', 'Toronto'), ('VIENNA', 'Vienna'), ('WARSAW', 'Warsaw'), ('ZUG', 'Zug'), ('ZURICH', 'Zurich'), ('OTHER', 'Other')], max_length=150, null=True),
        ),
    ]
