# Generated by Django 5.1.6 on 2025-05-14 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_userprofile_city'),
        ('user', '0006_user_source_alter_userprofile_city'),
    ]

    operations = [
    ]
