# Generated by Django 5.1.6 on 2025-04-18 08:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='meetinginformation',
            name='information_saved_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_saved_meeting_informations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='meetingimage',
            name='meeting_information',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_images', to='events.meetinginformation'),
        ),
        migrations.AddField(
            model_name='userevent',
            name='base_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_events', to='events.baseevent'),
        ),
        migrations.AddField(
            model_name='userevent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usernetwork',
            name='base_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_networks', to='events.baseevent'),
        ),
        migrations.AddField(
            model_name='usernetwork',
            name='scanned',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scanned_by_others', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usernetwork',
            name='scanner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scanned_others', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='meetinginformation',
            name='network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='events.usernetwork'),
        ),
        migrations.AddConstraint(
            model_name='userevent',
            constraint=models.UniqueConstraint(fields=('user', 'base_event'), name='unique_user_event_view'),
        ),
        migrations.AddConstraint(
            model_name='usernetwork',
            constraint=models.UniqueConstraint(fields=('scanner', 'scanned'), name='unique_network_connection'),
        ),
    ]
