# Generated by Django 5.1.6 on 2025-04-19 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_userevent_code_alter_userevent_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernetwork',
            name='scanned_event_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='usernetwork',
            name='scanner_event_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
