# Generated by Django 5.1.6 on 2025-04-24 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_usernetwork_scanned_event_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseevent',
            name='code',
            field=models.SlugField(max_length=100),
        ),
        migrations.AlterField(
            model_name='baseevent',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
