# Generated by Django 5.1.6 on 2025-05-09 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_spamreport_walletconnection_networkingrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkingrequest',
            name='amount_staked',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='networkingrequest',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
