# Generated by Django 5.1.6 on 2025-05-14 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_create_notification_model'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
