# Generated by Django 5.1.6 on 2025-05-15 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_delete_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkingrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('spam', 'Spam'), ('removed', 'Removed')], default='pending', max_length=20),
        ),
    ]
