# Generated by Django 5.1.6 on 2025-05-17 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_alter_networkingrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkingrequest',
            name='escrow_account',
            field=models.CharField(blank=True, max_length=44, null=True),
        ),
        migrations.AddField(
            model_name='networkingrequest',
            name='receiver_wallet',
            field=models.CharField(blank=True, max_length=44, null=True),
        ),
        migrations.AddField(
            model_name='networkingrequest',
            name='request_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='networkingrequest',
            name='sender_wallet',
            field=models.CharField(blank=True, max_length=44, null=True),
        ),
        migrations.AddField(
            model_name='networkingrequest',
            name='tx_signature',
            field=models.CharField(blank=True, max_length=88, null=True),
        ),
    ]
