version: '3.3'

services:
  web:
    container_name: zefe_web
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    # command: gunicorn core.wsgi:application --workers=3 --bind 0.0.0.0:8000

    stdin_open: true
    tty: true
    volumes:
      - .:/app
    ports:
      - 8000:8000
    env_file:
      - ./.env
    # depends_on:
      # - db

  # db:
  #   container_name: zefe_db
  #   image: postgres:13.0-alpine
  #   volumes:
  #     - db_data:/var/lib/postgresql/data/
  #   ports:
  #     - 5432:5432
  #   env_file:
  #     - ./.env

volumes:
  db_data:



